### ISSUE TITLE
Fatal error when activating plugin

### ISSUE THREAD

**Issue by mattjohnlee** [Chalkbeat/MORI#2]
Following the installation instructions, when I click "activate" on the MORI plugin, I receive this message:

`Fatal error: Call to undefined function is_plugin_active() in /srv/www/wordpress-thetrace/wp-content/plugins/chalkbeat-MORI/mori.php on line 38`

Looking at line 39 in mori.php, I noticed the comment re: older installations of MORI. Since this didn't apply to me, I commented out lines 38-41 as a temporary fix, and installation seems to work.

**Comment by cjhickerson** [comment]
Glad you were able to work around that. I'll be moving all the features related to older versions on MORI into a different plugin very soon. That should eliminate this issue long term.

**Comment by cjhickerson** [comment]
This should be resolved now. Sorry for that wait.
