### ISSUE TITLE
Fatal error: Uncaught Error: Call to undefined function is_plugin_active()

### ISSUE THREAD

**Issue by benlk** [Chalkbeat/MORI#5]
> Fatal error: Uncaught Error: Call to undefined function is_plugin_active() in /wp-content/plugins/chalkbeat-MORI/mori.php:38 Stack trace: #0 /wp-includes/plugin.php(524): {closure}('') #1 /wp-settings.php(411): do_action('init') #2 /wp-config.php(83): require_once('/Users/blk/site...') #3 /wp-load.php(39): require_once('/Users/blk/site...') #4 /wp-blog-header.php(13): require_once('/Users/blk/site...') #5 /index.php(17): require('/Users/blk/site...') #6 /Users/blk/.composer/vendor/laravel/valet/server.php(147): require('/Users/blk/site...') #7 {main} thrown in /wp-content/plugins/chalkbeat-MORI/mori.php on line 38

Seen on the front page of a site, without being logged in. The following plugins were active besides MORI:

```
$ wp plugin list
+--------------------------------------+----------+-----------+----------+
| name                                 | status   | update    | version  |
+--------------------------------------+----------+-----------+----------+
| akismet                              | active   | available | 3.2      |
| gravityforms                         | active   | available | 2.0-rc-1 |
| gravity-forms-add-subtotal-merge-tag | inactive | none      | 1.0      |
| gravityformsmailchimp                | active   | available | 3.7.1    |
| gravityformsstripe                   | active   | available | 2.0.2    |
| hello                                | inactive | none      | 1.6      |
| chalkbeat-MORI                       | inactive | none      | 0.1      |
| presspoint                           | active   | none      | 3.4.4    |
| pym-shortcode                        | active   | none      | 1.3.2.1  |
| super-cool-ad-inserter               | active   | none      | 0.1.1    |
+--------------------------------------+----------+-----------+----------+
```

This error is concerning because is_plugin_active probably should not be being called on non-admin pages. https://codex.wordpress.org/Function_Reference/is_plugin_active

**Comment by cjhickerson** [comment]
The simplest solution here would be to remove that section of code entirely. It's only relevant to people running the 1.x versions of MORI which shouldn't be anyone anymore. 

I'll get on that this afternoon.

**Comment by cjhickerson** [comment]
Looking at this closer I think they are using an old version. The current version on master doesn't have the migrations code that is throwing the error here. 

Could you try grabbing the current master and running that?

**Comment by benlk** [comment]
Yes, this error is fixed in the current master version of the plugin.
